//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasProgramadas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> FechaDeCreacion { get; set; }
        public int Asignador { get; set; }
        public string TituloTarea { get; set; }
        public string Descripcion { get; set; }
        public int Asignado { get; set; }
        public Nullable<System.DateTime> FechaDeProximoEvento { get; set; }
        public string Frecuencia { get; set; }
        public string Finalizada { get; set; }
    
        public virtual CT_Users CT_Users { get; set; }
        public virtual CT_Users CT_Users1 { get; set; }
    }
}
